name: Release

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4

      - name: 构建Java环境
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 解码生成 jks
        run: echo $KEYSTORE_BASE64 | base64 -di > app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: 生成apk
        run: chmod +x ./gradlew && ./gradlew assembleRelease

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: 重命名应用
        run: |
          for file in app/build/outputs/apk/release/app-*.apk; do
            new_file_name="app/build/outputs/apk/release/mytv-android.apk"
            echo "Renaming APK to: $new_file_name"
            mv "$file" "$new_file_name"
          done

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp app/build/outputs/apk/release/*.apk artifacts/

      - name: Upload Caddy Binary
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          files: |
            artifacts/*
